using Microsoft.AspNetCore.SignalR;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using TNDStudios.AppMonitor.Objects;

namespace TNDStudios.AppMonitor.Core
{
    public class AppMonitorHubBase : Hub
    {
        /// <summary>
        /// INjected core service from the Singleton provided at setup
        /// </summary>
        private readonly IAppMonitorCoordinator coordinator;

        /// <summary>
        /// Default constructor with the App Monitor Core injected into it
        /// </summary>
        public AppMonitorHubBase(IAppMonitorCoordinator coordinator)
        {
            this.coordinator = coordinator;
        }

        /// <summary>
        /// Generate a reporting summary for warboards etc.
        /// </summary>
        /// <returns>The consolidated reporting summary</returns>
        public ReportingSummary GetReportingSummary()
        {
            // Create a blank report as we won't be returning everything
            ReportingSummary reportingSummary =
                new ReportingSummary()
                {
                    Applications = new List<ReportingApplication>()
                };

            // Loop all the applications

            return reportingSummary;
        }

        /// <summary>
        /// A metric was received from an application
        /// </summary>
        /// <param name="applicationName">The name of the application</param>
        /// <param name="path">The path for the metric seperated with pipes</param>
        /// <param name="metric">The value of the metric</param>
        /// <returns></returns>
        public async Task SendMetric(string applicationName, string path, Double metric)
        {
            ReportingApplication application = coordinator.GetApplication(applicationName);
#if DEBUG
#warning Summarise and locking needed so that metrics can be added by path and summary
#endif
            //application.Metrics.Add(new ReportingMetric() { Path = path, Value = metric });

            // Tell all the clients a new metric was received
            await Clients.All.SendAsync("ReceiveMetric", applicationName, path, metric);
        }

        /// <summary>
        /// An error was recieved from an application via SignalR
        /// </summary>
        /// <param name="applicationName">The name of the application</param>
        /// <param name="errorMessage">The error message as generated by the application</param>
        /// <returns></returns>
        public async Task SendError(string applicationName, string errorMessage)
        {
            // Get the application from the coordinator
            ReportingApplication application = coordinator.GetApplication(applicationName);

            // Add the error to the memory error list for this application
            application.Errors.Add(new ReportingError() { Message = errorMessage });

            // Tell all the clients a new error was received
            await Clients.All.SendAsync("ReceiveError", applicationName, errorMessage);
        }
    }
}
